/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ProjectTemplate } from '../types/types';

export const TEMPLATES: Record<string, ProjectTemplate> = {
  construction: {
    name: 'Commercial Building Construction',
    description: 'An enterprise-level substructure and superstructure building schedule with nested WBS layers, structural dependencies, and critical path branches.',
    nodes: [
      // Level 1: Apex Building Construction
      {
        id: 'wbs-root',
        code: '1',
        name: 'Apex Office Building Construction',
        parentId: null,
        type: 'wbs',
        isExpanded: true,
        startDate: '2026-06-01',
        endDate: '2026-07-28',
        duration: 42,
        progress: 0,
      },
      // Level 1.1: Design & Approval (WBS)
      {
        id: 'wbs-design',
        code: '1.1',
        name: 'Design, Engineering & Permitting',
        parentId: 'wbs-root',
        type: 'wbs',
        isExpanded: true,
        startDate: '2026-06-01',
        endDate: '2026-06-19',
        duration: 15,
        progress: 0,
      },
      {
        id: 'act-blueprints',
        code: 'A1000',
        name: 'Prepare Architectural Blueprints & Layout',
        parentId: 'wbs-design',
        type: 'activity',
        startDate: '2026-06-01',
        endDate: '2026-06-05',
        duration: 5,
        progress: 45,
        resources: ['Principal Architect', 'Drafting Specialist'],
        constraintType: 'ASAP',
        notes: 'Includes draft review with safety board and occupancy engineers.',
      },
      {
        id: 'act-structural',
        code: 'A1010',
        name: 'Structural Engineering Calculations & Wind Loads',
        parentId: 'wbs-design',
        type: 'activity',
        startDate: '2026-06-08',
        endDate: '2026-06-11',
        duration: 4,
        progress: 10,
        resources: ['Structural Engineer (SE)'],
        constraintType: 'ASAP',
        notes: 'Verify wind-resistance compliance for upper levels.',
      },
      {
        id: 'act-permits',
        code: 'A1020',
        name: 'County Review & Excavation Permit Approval',
        parentId: 'wbs-design',
        type: 'activity',
        startDate: '2026-06-12',
        endDate: '2026-06-19',
        duration: 6,
        progress: 0,
        resources: ['Project Planner', 'County Liaison'],
        constraintType: 'ASAP',
        notes: 'Critical regulatory gateway. Construction crew is on standby.',
      },

      // Level 1.2: Civil Engineering & Foundation (WBS)
      {
        id: 'wbs-foundation',
        code: '1.2',
        name: 'Site Preparation & Foundation Works',
        parentId: 'wbs-root',
        type: 'wbs',
        isExpanded: true,
        startDate: '2026-06-22',
        endDate: '2026-07-09',
        duration: 14,
        progress: 0,
      },
      {
        id: 'act-excavate',
        code: 'A1030',
        name: 'Excavation, Hauling & Grading',
        parentId: 'wbs-foundation',
        type: 'activity',
        startDate: '2026-06-22',
        endDate: '2026-06-26',
        duration: 5,
        progress: 0,
        resources: ['Excavator Crew', 'Heavy Equipment Op'],
        constraintType: 'ASAP',
        notes: 'Haul dirt to recycling yard. Prepare drainage paths.',
      },
      {
        id: 'act-framing-found',
        code: 'A1040',
        name: 'Pour Concrete Footings & Utility Rough-Ins',
        parentId: 'wbs-foundation',
        type: 'activity',
        startDate: '2026-06-29',
        endDate: '2026-07-02',
        duration: 4,
        progress: 0,
        resources: ['Masonry Crew', 'Plumbing Sub'],
        constraintType: 'ASAP',
        notes: 'Must cure for 48 hours before steel load is introduced.',
      },
      {
        id: 'act-retaining',
        code: 'A1050',
        name: 'Retaining Wall & Sub-Slab Moisture Barrier',
        parentId: 'wbs-foundation',
        type: 'activity',
        startDate: '2026-07-03',
        endDate: '2026-07-09',
        duration: 5,
        progress: 0,
        resources: ['Waterproofing Tech', 'Foundations Specialist'],
        constraintType: 'ASAP',
        notes: 'Imperative barrier to prevent ground moisture seepage.',
      },

      // Level 1.3: Superstructure Frame (WBS)
      {
        id: 'wbs-super',
        code: '1.3',
        name: 'Superstructure Framing & Slabs',
        parentId: 'wbs-root',
        type: 'wbs',
        isExpanded: true,
        startDate: '2026-07-10',
        endDate: '2026-07-28',
        duration: 13,
        progress: 0,
      },
      {
        id: 'act-steel-columns',
        code: 'A1060',
        name: 'Erect Structural Steel Columns & Beams',
        parentId: 'wbs-super',
        type: 'activity',
        startDate: '2026-07-10',
        endDate: '2026-07-17',
        duration: 6,
        progress: 0,
        resources: ['Ironworkers Crew', 'Mobile Crane Operator'],
        constraintType: 'ASAP',
        notes: 'Crane scheduled for 5 working days starting July 10.',
      },
      {
        id: 'act-floor-slabs',
        code: 'A1070',
        name: 'Pour Composite Metal Floor Slabs',
        parentId: 'wbs-super',
        type: 'activity',
        startDate: '2026-07-20',
        endDate: '2026-07-28',
        duration: 7,
        progress: 0,
        resources: ['Concrete Crew', 'Pump Truck Operator'],
        constraintType: 'ASAP',
        notes: 'Upper deck staging setup.',
      },

      // Level 1.4: Exterior Enclosure & HVAC (WBS)
      {
        id: 'wbs-envelope',
        code: '1.4',
        name: 'Exterior Siding, HVAC & Mechanical',
        parentId: 'wbs-root',
        type: 'wbs',
        isExpanded: true,
        startDate: '2026-07-29',
        endDate: '2026-08-14',
        duration: 13,
        progress: 0,
      },
      {
        id: 'act-curtain-wall',
        code: 'A1080',
        name: 'Install Glass Curtain Walls & Envelope Siding',
        parentId: 'wbs-envelope',
        type: 'activity',
        startDate: '2026-07-29',
        endDate: '2026-08-06',
        duration: 7,
        progress: 0,
        resources: ['Glazing Crew', 'Facades Specialist'],
        constraintType: 'ASAP',
        notes: 'Makes the structure weather-tight.',
      },
      {
        id: 'act-hvac-rough',
        code: 'A1090',
        name: 'HVAC Ductwork & Electrical Panels Rough-In',
        parentId: 'wbs-envelope',
        type: 'activity',
        startDate: '2026-07-29',
        endDate: '2026-08-07',
        duration: 8,
        progress: 0,
        resources: ['HVAC Subcontractor', 'Electrical Tech'],
        constraintType: 'ASAP',
        notes: 'Parallel track to glazing. Inter-dependent safety inspection.',
      },
      {
        id: 'act-drywall',
        code: 'A1100',
        name: 'Interior Insulation, Drywall Boarding & Paint',
        parentId: 'wbs-envelope',
        type: 'activity',
        startDate: '2026-08-10',
        endDate: '2026-08-14',
        duration: 5,
        progress: 0,
        resources: ['Drywall Installer', 'Finishes Crew'],
        constraintType: 'ASAP',
        notes: 'Readying base layers for client design teams.',
      }
    ],
    dependencies: [
      { id: 'dep-1', fromId: 'act-blueprints', toId: 'act-structural', type: 'FS', lag: 0 },
      { id: 'dep-2', fromId: 'act-structural', toId: 'act-permits', type: 'FS', lag: 0 },
      { id: 'dep-3', fromId: 'act-permits', toId: 'act-excavate', type: 'FS', lag: 0 },
      { id: 'dep-4', fromId: 'act-excavate', toId: 'act-framing-found', type: 'FS', lag: 0 },
      { id: 'dep-5', fromId: 'act-framing-found', toId: 'act-retaining', type: 'FS', lag: 0 },
      { id: 'dep-6', fromId: 'act-retaining', toId: 'act-steel-columns', type: 'FS', lag: 0 },
      { id: 'dep-7', fromId: 'act-steel-columns', toId: 'act-floor-slabs', type: 'FS', lag: 0 },
      { id: 'dep-8', fromId: 'act-floor-slabs', toId: 'act-curtain-wall', type: 'FS', lag: 0 },
      { id: 'dep-9', fromId: 'act-floor-slabs', toId: 'act-hvac-rough', type: 'FS', lag: 0 },
      { id: 'dep-10', fromId: 'act-hvac-rough', toId: 'act-drywall', type: 'FS', lag: 0 }
    ],
  },

  software: {
    name: 'Enterprise App Release (V2.4)',
    description: 'Software launch and engineering plan outlining sprint grooming, core infrastructure development, QA cycles, multi-stage deployments, and legal compliance.',
    nodes: [
      // Root Software Release
      {
        id: 'sw-root',
        code: '1',
        name: 'V2.4 Product Release Management',
        parentId: null,
        type: 'wbs',
        isExpanded: true,
        startDate: '2026-06-01',
        endDate: '2026-07-10',
        duration: 30,
        progress: 0,
      },
      // Design & Grooming
      {
        id: 'sw-wbs-prep',
        code: '1.1',
        name: 'Scoping, Figma and Sprint Planning',
        parentId: 'sw-root',
        type: 'wbs',
        isExpanded: true,
        startDate: '2026-06-01',
        endDate: '2026-06-09',
        duration: 7,
        progress: 0,
      },
      {
        id: 'sw-figma',
        code: 'S1000',
        name: 'UI/UX Interactive Figma Screen Lock-In',
        parentId: 'sw-wbs-prep',
        type: 'activity',
        startDate: '2026-06-01',
        endDate: '2026-06-04',
        duration: 4,
        progress: 90,
        resources: ['Product Designer'],
        constraintType: 'ASAP',
        notes: 'Obtain alignment from enterprise tech leads before starting sprints.',
      },
      {
        id: 'sw-db-design',
        code: 'S1010',
        name: 'Database Schema Design & Migration Scripts',
        parentId: 'sw-wbs-prep',
        type: 'activity',
        startDate: '2026-06-05',
        endDate: '2026-06-09',
        duration: 3,
        progress: 20,
        resources: ['Database Engineer', 'Tech Lead'],
        constraintType: 'ASAP',
        notes: 'Verify compatibility with cloud replicas.',
      },

      // Front & Back End Implementation
      {
        id: 'sw-wbs-coding',
        code: '1.2',
        name: 'Core Application Development Sprints',
        parentId: 'sw-root',
        type: 'wbs',
        isExpanded: true,
        startDate: '2026-06-10',
        endDate: '2026-06-25',
        duration: 12,
        progress: 0,
      },
      {
        id: 'sw-backend-api',
        code: 'S1020',
        name: 'GraphQL API Server Development & Docker Setup',
        parentId: 'sw-wbs-coding',
        type: 'activity',
        startDate: '2026-06-10',
        endDate: '2026-06-17',
        duration: 6,
        progress: 0,
        resources: ['Backend Software Eng (SE)'],
        constraintType: 'ASAP',
        notes: 'Implement OAuth tokens and rate limiting limits.',
      },
      {
        id: 'sw-frontend-ui',
        code: 'S1030',
        name: 'React SPA Client Integration & Tailwind Themes',
        parentId: 'sw-wbs-coding',
        type: 'activity',
        startDate: '2026-06-18',
        endDate: '2026-06-25',
        duration: 6,
        progress: 0,
        resources: ['Frontend Tech Lead', 'UI Developer'],
        constraintType: 'ASAP',
        notes: 'Connect with GraphQL server routes.',
      },

      // Quality Assurance
      {
        id: 'sw-wbs-qa',
        code: '1.3',
        name: 'Rigorous Quality Audit & Compliance',
        parentId: 'sw-root',
        type: 'wbs',
        isExpanded: true,
        startDate: '2026-06-26',
        endDate: '2026-07-07',
        duration: 8,
        progress: 0,
      },
      {
        id: 'sw-qa-test',
        code: 'S1040',
        name: 'Penetration Security Scan & Cross-Browser QA',
        parentId: 'sw-wbs-qa',
        type: 'activity',
        startDate: '2026-06-26',
        endDate: '2026-07-02',
        duration: 5,
        progress: 0,
        resources: ['Security Assessor', 'QA Engineers Team'],
        constraintType: 'ASAP',
        notes: 'All OWASP vulnerabilities must be closed.',
      },
      {
        id: 'sw-compliance',
        code: 'S1050',
        name: 'GDPR / HIPAA Storage Audit & Certification',
        parentId: 'sw-wbs-qa',
        type: 'activity',
        startDate: '2026-07-03',
        endDate: '2026-07-07',
        duration: 3,
        progress: 0,
        resources: ['Corporate Legal Counsel'],
        constraintType: 'ASAP',
        notes: 'Mandatory documentation sign-off for public clouds.',
      },

      // Rollout
      {
        id: 'sw-wbs-rollout',
        code: '1.4',
        name: 'Staging, Smoke Tests, Global Canaries',
        parentId: 'sw-root',
        type: 'wbs',
        isExpanded: true,
        startDate: '2026-07-08',
        endDate: '2026-07-10',
        duration: 3,
        progress: 0,
      },
      {
        id: 'sw-deploy',
        code: 'S1060',
        name: 'Global Deployment with Canary Trailing Webhook',
        parentId: 'sw-wbs-rollout',
        type: 'activity',
        startDate: '2026-07-08',
        endDate: '2026-07-10',
        duration: 3,
        progress: 0,
        resources: ['Site Reliability Engineer (SRE)'],
        constraintType: 'ASAP',
        notes: 'Incremental deployment (5%, 25%, 100%) to Cloud Run endpoints.',
      }
    ],
    dependencies: [
      { id: 'sw-dep-1', fromId: 'sw-figma', toId: 'sw-db-design', type: 'FS', lag: 0 },
      { id: 'sw-dep-2', fromId: 'sw-db-design', toId: 'sw-backend-api', type: 'FS', lag: 0 },
      { id: 'sw-dep-3', fromId: 'sw-backend-api', toId: 'sw-frontend-ui', type: 'FS', lag: 0 },
      { id: 'sw-dep-4', fromId: 'sw-frontend-ui', toId: 'sw-qa-test', type: 'FS', lag: 0 },
      { id: 'sw-dep-5', fromId: 'sw-qa-test', toId: 'sw-compliance', type: 'FS', lag: 0 },
      { id: 'sw-dep-6', fromId: 'sw-compliance', toId: 'sw-deploy', type: 'FS', lag: 0 }
    ],
  },
};
